[passwords]

"bourez.rudy@gmail.com" = "admin123456"
"florian.abgrall750@gmail.com" = "admin123456"
"john.doe@gmail.com" = "123456"
"patricia.meurey@gmail.com" = "123456"
"patrick.smith@gmail.com" = "123456"
"catherine.potin@gmail.com" = "123456"
"robert.pattinson@gmail.com" = "123456"
